<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>true</ImplicitUsings>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Configurations>Debug R21;Debug R22;Debug R23;Debug R24;Debug R25;Debug R26</Configurations>
        <Configurations>$(Configurations);Release R21;Release R22;Release R23;Release R24;Release R25;Release R26</Configurations>
    </PropertyGroup>

    <!-- Revit configuration -->
    <PropertyGroup Condition="$(Configuration.Contains('R21'))">
        <RevitVersion>2021</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R22'))">
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R23'))">
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R26'))">
        <RevitVersion>2026</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>

    <!-- Launch configuration -->
    <PropertyGroup>
        <StartAction>Program</StartAction>
        <StartProgram>C:\Program Files\Autodesk\Revit $(RevitVersion)\Revit.exe</StartProgram>
        <StartArguments>/language ENG</StartArguments>
    </PropertyGroup>

    <!-- Build configuration -->
    <!-- https://github.com/Nice3point/Revit.Build.Tasks -->
    <PropertyGroup>
        <IsRepackable>false</IsRepackable>
        <DeployRevitAddin>true</DeployRevitAddin>
    </PropertyGroup>
    <ItemGroup>
      <None Remove="Resources\Icons16\*" />
      <None Remove="Resources\Icons32\*" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="Resources\Icons16\*" />
      <EmbeddedResource Include="Resources\Icons32\*" />
    </ItemGroup>

    <ItemGroup>
        <!-- Revit References -->
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="3.0.1" />
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />
    </ItemGroup>
    
    <ItemGroup>
        <Resource Include="Resources\Icons\RibbonIcon16.png" />
        <Resource Include="Resources\Icons\RibbonIcon32.png" />
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Resources\Files\Tooltips.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Tooltips.resx</DependentUpon>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <EmbeddedResource Update="Resources\Files\Tooltips.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Tooltips.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
    
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="if not exist &quot;%25AppData%25\Autodesk\Revit\Addins\2025\AVES&quot; mkdir &quot;%25AppData%25\Autodesk\Revit\Addins\2025\AVES&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;%25AppData%25\Autodesk\Revit\Addins\2025\AVES\&quot; /Y /R /I&#xD;&#xA;" />
    </Target>

</Project>